os: osx
# These represent OS X 10.10 - 10.13
osx_image:
  - xcode10
  - xcode9.2
  - xcode8
  - xcode6.4
env:
  matrix:
    - CASK=pdk
    - CASK=puppet-agent
    - CASK=puppet-bolt
script:
  - brew cask install Casks/$CASK.rb --force
matrix:
  exclude:
    - osx_image: xcode6.4
      env: CASK=pdk
    - osx_image: xcode6.4
      env: CASK=puppet-bolt
