os: osx
# These represent OS X 10.14 - 11.3.
osx_image:
  - xcode12.5 # 11.3
  - xcode12.2 # 10.15
  - xcode10.2 # 10.14
branches:
  only:
    - master
env:
  global:
    - HOMEBREW_LOGS=~/homebrew-logs
    - HOMEBREW_TEMP=~/homebrew-temp
    - HOMEBREW_NO_AUTO_UPDATE=1
  matrix:
    - CASK=pe-client-tools
    - CASK=pe-client-tools-2019.8
    - CASK=pdk
    - CASK=puppet-agent
    - CASK=puppet-agent-6
    - CASK=puppet-agent-7
    - CASK=puppet-bolt
    - CASK=puppet-bolt@2
addons:
  homebrew:
    update: true
script:
  - brew install --cask Casks/$CASK.rb --force
matrix:
  include:
    - osx_image: xcode10.2
      env: FORMULA=wash
      script: brew install Formula/$FORMULA.rb
    - osx_image: xcode10.2
      env: FORMULA=relay
      script: brew install Formula/$FORMULA.rb
