os: osx
# These represent OS X 10.12 - 10.14.
# Extra matrix entries add OS X 10.10 - 10.11.
osx_image:
  - xcode10.2
  - xcode10
  - xcode9.2
env:
  global:
    - HOMEBREW_LOGS=~/homebrew-logs
    - HOMEBREW_TEMP=~/homebrew-temp
  matrix:
    - CASK=pdk
    - CASK=puppet-agent
    - CASK=puppet-agent-5
    - CASK=puppet-agent-6
    - CASK=puppet-bolt
script:
  - brew cask install Casks/$CASK.rb --force
matrix:
  include:
    - osx_image: xcode8
      env: CASK=pdk
    - osx_image: xcode6.4
      env: CASK=puppet-agent-5
    - osx_image: xcode8
      env: CASK=puppet-agent-5
    - osx_image: xcode8
      env: CASK=puppet-bolt
